### PR TITLE
[Fixes #71] Play 2.4 support

### LINKED ISSUE #71: Play 2.4 support
https://github.com/aselab/scala-activerecord/tree/master/play2
https://www.playframework.com/documentation/2.4.x/Modules
https://www.playframework.com/documentation/2.4.x/ScalaDependencyInjection

* Migration from Plugin to Module

### PR DESCRIPTION
**Pull request by pcboy**
Fixes #71. Support for Play 2.4.

### CODE REVIEW

**Comment by mediavrog** [comment]
LGTM!
[LGTM](http://lgtm.in/i/ECzmxJZcq)

[:+1:](http://lgtm.in/u/ECzmxJZcq) [:-1:](http://lgtm.in/r/ECzmxJZcq)

**Comment by thepratt** [comment]
How does this add support for Play 2.4? Plugins are deprecated in 2.4, modules should be used now [https://www.playframework.com/documentation/2.4.x/ScalaPlugins].
WIth a fresh 2.4.2 install, and following Play2+ ActiveRecord README, ActiveRecord is broken for Play 2.4+.

The following occurs when using scala-activerecord 0.3.1:
play.api.UnexpectedException: Unexpected exception[ConfigurationException: Guice configuration errors:

1) Could not find a suitable constructor in com.github.aselab.activerecord.ActiveRecordPlugin. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
  at com.github.aselab.activerecord.ActiveRecordPlugin.class(ActiveRecordPlugin.scala:6)
  while locating com.github.aselab.activerecord.ActiveRecordPlugin

**Comment by knshiro** [comment]
Just use 0.3.2. The README is just outdated.

**Comment by thepratt** [comment]
@knshiro The latest release is 0.3.1?

**Comment by knshiro** [comment]
My bad they didn't release 0.3.2
You will need to build the latest build yourself to try. ( sbt publish-local)

**Pull request merged**
